[[rule]]
pattern = "insurance"
account = "expenses:insurance"

[[rule]]
pattern = "service charge"
account = "expenses:bank_fees"

[[rule]]
pattern = "interest payment"
account = "income:interest"

[[rule]]
pattern = "landscaping"
account = "expenses:landscaping"

[[rule]]
pattern = "Transfer to Checking"
account = "Checking"
