[[rule]]
pattern = "ONLINE FROM (\\**)9625 - TRUIST ONLINE TRANSFER"
replacement = "Transfer from Savings"

[[rule]]
pattern = "ONLINE TO (\\**)0947 - TRUIST DEPOSIT TRANSFER"
replacement = "Transfer to Checking"

[[rule]]
pattern = "TRUIST DEPOSIT TRANSFER ONLINE FROM (\\**)0947 -"
replacement = "Transfer from Checking"

[[rule]]
pattern = "TRUIST ONLINE TRANSFER ONLINE TO (\\**)9625 -"
replacement = "Transfer to Savings"

[[rule]]
pattern = "(EFFECTIVE DATE (\\d\\d-\\d\\d-\\d\\d) )?INTEREST PAYMENT"
replacement = "Interest Payment"

[[rule]]
pattern = "CASHOUT VENMO (\\d+) JASON STEWART ACH CREDIT"
replacement = "Venmo transfer - \\1"

[[rule]]
pattern = "PAYMENT VENMO ([*\\d]+) INTERNET PAYMENT"
replacement = "Venmo Payment (\\1)"

[[rule]]
pattern = "ADDFUNDS VENMO ([*\\d]+) INTERNET PAYMENT"
replacement = "Venmo Add Funds (\\1)"

[[rule]]
pattern = "EDI PYMNTS ((NATIONWIDE INS)|(NWEDI-(\\d*))) FLEX(\\d*) INTERNET PAYMENT"
replacement = "Nationwide Insurance Payment"

[[rule]]
pattern = "Check #(\\d+)"
replacement = "San Remo Landscaping"
amount = 250.00
type = ["Check", "Debit"]
